### ISSUE TITLE
Error when Running "mochaTest:dist" (mochaTest) task

### ISSUE THREAD

**Issue by Qhorin** [Anahkiasen/cookie-monster#43]
I believe I've found a fix for the latest CookieMonster freeze. I was about to submit a pull request for review, but saw that the contribution guidelines wanted me to run `grunt test`

So I ran the following, and received an error. Any ideas?

```
$ ./node_modules/.bin/grunt test
Running "mochaTest:dist" (mochaTest) task
>> Mocha exploded!
>> Error: BLANKET-Error parsing instrumented code: TypeError: Property '$' of object #<Object> is not a function
>>     at /home/user/cookie-monster/node_modules/blanket/src/index.js:167:35
>>     at Object.blanket._blanket.instrument (/home/user/cookie-monster/node_modules/blanket/src/blanket.js:125:17)
>>     at Object.require.extensions..js (/home/user/cookie-monster/node_modules/blanket/src/index.js:148:25)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (/home/user/cookie-monster/tests/tests.js:25:17)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
Warning: Task "mochaTest:dist" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by Gotos** [comment]
Thanks so much! I just downloaded your fork and tried it and it works. I hope the tests not running will be fixed soon, so your fix makes it into the next release.

**Comment by Qhorin** [comment]
@Gotos  No problem. After I wrote the fix, I found another issue. The Warning and Caution notes are drawn on top of the new Clicker stats tooltip, but at least CM works now. It looks like the Clicker code introduced a dynamic tooltip which is a little tricky to append to. I'm still working on that part.

**Comment by Gotos** [comment]
@Qhorin Yeah, I saw that later today, but that's still better then not being able to use CM :)

**Comment by Qhorin** [comment]
Edit: "fixNotes" was merged into upstream 'develop'. I deleted fixNotes after merge.

@Gotos I just pushed code to a new branch "fixNotes'' to my fork that moves the Warning and Caution notes below the tooltip. Try it out and let me know if you see any problems. https://github.com/Qhorin/cookie-monster/tree/fixNotes
